version: '3.8'

services:
  app:
    image: node:16-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm test && npm start"
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
  
volumes:
  postgres-data: